SELECT STR_TO_DATE(CONCAT(A.YEAR, A.MONTH, A.DAY), '%Y%b%d') AS HIT_DATE, 
COUNT(*) AS HIT_COUNT
FROM 
(select  
DATETIME1, 
	SUBSTRING(DATETIME1, 2, 2) AS DAY, 
    SUBSTRING(DATETIME1, 5, 3) AS MONTH, 
    SUBSTRING(DATETIME1, 9, 4) AS YEAR 
    from hits_archive where COUNTRY = "United States") A 
GROUP BY STR_TO_DATE(CONCAT(A.YEAR, A.MONTH, A.DAY), '%Y%b%d');